#pragma once

enum Screen {
    SCREEN_MAIN,
    SCREEN_SETTINGS,
    SCREEN_CONNECTIVITY,
    SCREEN_SETTING_BATTERY,
    SCREEN_SETTING_UPDATE,
    SCREEN_ABOUT,
    SCREEN_SETTING_WIFI,
    SCREEN_SETTING_ESP_NOW,
    SCREEN_SETTING_WIFI_ADD,
    SCREEN_SETTING_BRIGHTNESS,
    SCREEN_SETTING_BRIGHTNESS_OLED,
    SCREEN_SETTING_BRIGHTNESS_BLADE
};